blog/urls.py
from django.urls import path

from blog.views import BlogListView, BlogCreateView, BlogUpdateView, BlogDeleteView, BlogDetailView

app_name = 'blog'

urlpatterns = [
    path("home/", BlogListView.as_view(), name="home"),
    path("add_article/", BlogCreateView.as_view(), name="add_article"),
    path("update_article/<int:pk>/edit/", BlogUpdateView.as_view(), name="update_article"),
    path("blog_confirm_delete/<int:pk>/delete/", BlogDeleteView.as_view(), name="blog_confirm_delete"),
    path("blog_detail/<int:pk>/", BlogDetailView.as_view(), name="blog_detail"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import RegisterView, UserLoginView, UserProfileEdit

# from .views import ProductListView, ContactFormView, ProductDetailView, ProductCreateView, ProductUpdateView, \
#     ProductDeleteView

app_name = UsersConfig.name

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(next_page='catalog:home'), name='login'),
    path('logout/', LogoutView.as_view(next_page='catalog:home'), name='logout'),
    path('profile/<int:pk>', UserProfileEdit.as_view(), name='profile'),
]

blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=150,
                             verbose_name="Заголовок",
                             blank=False,
                             null=False)

    content = models.TextField(verbose_name="Cодержание",
                               blank=False,
                               null=False)

    preview = models.ImageField(upload_to="images/",
                                verbose_name="Превью",
                                blank=True,
                                null=True)

    created_at = models.DateField(auto_now_add=True)

    is_published = models.BooleanField(verbose_name="Статус публикации")

    view_count = models.PositiveIntegerField(verbose_name="Количество просмотров",
                                             default=0)

    def __str__(self):
        return f"{self.title}\n {self.content}"

    class Meta:
        verbose_name = "Статья"
        verbose_name_plural = "Статьи"

blog/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from blog.models import Blog


class BlogCreateView(CreateView):
    model = Blog
    fields = ['title',
              'content',
              'preview',
              'is_published',
              ]
    template_name = "blog/add_article.html"
    success_url = reverse_lazy("blog:home")


class BlogListView(ListView):
    model = Blog
    paginate_by = 5
    template_name = "blog/home.html"
    context_object_name = 'blogs'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(is_published=True)


class BlogUpdateView(UpdateView):

    model = Blog
    fields = ['title',
              'content',
              'preview',
              'is_published',
              ]
    template_name = "blog/update_article.html"

    def form_valid(self, form):
        page = self.get_context_data()['object'].pk
        self.success_url = reverse_lazy('blog:blog_detail', kwargs={'pk': page})
        return super().form_valid(form)


class BlogDeleteView(DeleteView):
    model = Blog
    template_name = 'blog/blog_confirm_delete.html'
    success_url = reverse_lazy('blog:home')


class BlogDetailView(DetailView):
    model = Blog
    template_name = 'blog/blog_detail.html'
    context_object_name = 'blog'

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        obj.view_count += 1
        obj.save()
        return obj

blog/templates/blog/add_article.html
{% extends 'blog\base.html' %}

{% block title %} Написать статью {% endblock %}

{% block content %}

<main class="container mt-5">
<div class="p-4 p-md-5 mb-4 rounded text-body-emphasis bg-body-secondary">
    <div class="col-lg-6 px-0">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Сохранить</button>
                <a href="{% url 'blog:home' %}" class="btn btn-primary">Отмена</a>

            </form>
        </div>
    </div>
</main>
{% endblock %}

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <script defer src="/static/js/bootstrap.bundle.min.js"></script>
</head>
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="aperture" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
            stroke-width="2" viewBox="0 0 24 24">
        <circle cx="12" cy="12" r="10"/>
        <path d="M14.31 8l5.74 9.94M9.69 8h11.48M7.38 12l5.74-9.94M9.69 16L3.95 6.06M14.31 16H2.83m13.79-4l-5.74 9.94"/>
    </symbol>
    <symbol id="cart" viewBox="0 0 16 16">
        <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
    </symbol>
    <symbol id="chevron-right" viewBox="0 0 16 16">
        <path fill-rule="evenodd"
              d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z"/>
    </symbol>
</svg>
<div class="container mt-2">
{% include 'blog\base_header.html' %}
</div>
<body>
        {% block content %}{% endblock %}
</body>

blog/templates/blog/base_header.html
    <header class="border-bottom lh-1 py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
            <div class="col-4 pt-1">
                <a class="link-secondary" href="{% url 'blog:add_article' %}">Написать статью</a>
            </div>
            <div class="col-4 text-center">
                <a class="blog-header-logo text-body-emphasis text-decoration-none" href="{% url 'blog:home' %}">На главную</a>
            </div>
            <div class="col-4 d-flex justify-content-end align-items-center">
                <a class="link-secondary" href="#" aria-label="Search">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor"
                         stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="mx-3" role="img"
                         viewBox="0 0 24 24"><title>Поиск</title>
                        <circle cx="10.5" cy="10.5" r="7.5"/>
                        <path d="M21 21l-5.2-5.2"/>
                    </svg>
                </a>
                <a class="btn btn-sm btn-outline-secondary" href="{% url 'users:login'%}">Войти</a>
            </div>
        </div>
    </header>

blog/templates/blog/blog_confirm_delete.html
{% extends 'blog\base.html' %}

{% block title %} Удалить статью {% endblock %}

{% block content %}

<main class="container mt-5">
    <div class="container mt-5">
        <p>Вы уверены, что хотите удалить "{{ blog.title }}"?</p>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Удалить</button>
            <a href="{% url 'blog:home' %}" class="btn btn-primary">Отмена</a>
        </form>
    </div>
</main>

{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'blog\base.html' %}

{% block title %} Детали {% endblock %}

{% block content %}

<main class="container mt-5">
<div class="p-4 p-md-5 mb-4 rounded text-body-emphasis bg-body-secondary">
    <div class="col-lg-6 px-0">
      <p class="blog-post-meta"> {{ blog.title }} </p>
      <p> {{ blog.content }}</p>
      <p class="blog-post-meta">{{ blog.created_at|date:"d M Y" }} </p>
    </div>
  <a href="{% url 'blog:update_article' blog.pk %}" class="btn btn-secondary">Редактировать</a>
        <a href="{% url 'blog:blog_confirm_delete' blog.pk %}" class="btn btn-danger">Удалить</a>
        <a href="{% url 'blog:home' %}" class="btn btn-primary">Вернуться к списку</a>
</div>
</main>
{% endblock %}

blog/templates/blog/home.html
{% extends 'blog\base.html' %}

{% block title %}Главная страница{% endblock %}

{% block content %}
<main class="container mt-5 justify-content-center">
    <div class="row mb-2 ">
    </div>
    <div class="row g-5 ">
        <div class="col-md-8">
            <h3 class="pb-4 mb-4 fst-italic border-bottom text-center">
                Статьи
            </h3>
            {% for blog in blogs %}
            <article class="blog-post bg-info-subtle text-center">
                <p><a class="fs-3 fst-italic text-black link-offset-2 link-underline link-underline-opacity-0"
                      href="{% url 'blog:blog_detail' blog.pk %}">{{ blog.title }}</a></p>
                <p class="blog-post-meta text-end">Дата публикации: {{ blog.created_at|date:"d M Y" }} </p>
                <p class="blog-post-meta">{{ blog.content }} </p>
                <p class="blog-post-footer text-end">Просмотров: {{ blog.view_count }} </p>
            </article>
            {% endfor %}
            <nav aria-label="Навигация по страницам">
                <ul class="pagination justify-content-center">
                    {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link">Предыдущая</a>
                    </li>
                    {% endif %}
                    {% for page_product in page_obj.paginator.page_range %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_product }}">{{ page_product }}</a>
                    </li>
                    {% endfor %}
                    {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link"
                                             href="?page={{ page_obj.next_page_number }}">Следующая</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link">Следующая</a>
                    </li>
                    {% endif %}

                </ul>
            </nav>
        </div>
    </div>
</main>
{% endblock %}

blog/templates/blog/update_article.html
{% extends 'blog\base.html' %}

{% block title %} Обновление блога {% endblock %}

{% block content %}

<main class="container mt-5">
<div class="p-4 p-md-5 mb-4 rounded text-body-emphasis bg-body-secondary">
    <div class="col-lg-6 px-0">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Сохранить</button>
            <a href="{% url 'blog:home' %}" class="btn btn-primary">Отмена</a>
        </form>
    </div>
</div>
</main>
{% endblock %}