blog/urls.py
from django.urls import path

from blog.views import BlogListView, BlogCreateView, BlogUpdateView, BlogDeleteView, BlogDetailView

app_name = 'blog'

urlpatterns = [
    path("home/", BlogListView.as_view(), name="home"),
    path("add_article/", BlogCreateView.as_view(), name="add_article"),
    path("update_article/<int:pk>/edit/", BlogUpdateView.as_view(), name="update_article"),
    path("blog_confirm_delete/<int:pk>/delete/", BlogDeleteView.as_view(), name="blog_confirm_delete"),
    path("blog_detail/<int:pk>/", BlogDetailView.as_view(), name="blog_detail"),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import ProductListView, ContactFormView, ProductDetailView, ProductCreateView, ProductUpdateView, \
    ProductDeleteView, ProductsCategoryListView

app_name = 'catalog'

urlpatterns = [
    path("contacts/", ContactFormView.as_view(), name="contacts"),
    path("products/", ProductListView.as_view(), name="home"),
    path("products/<int:pk>/", ProductDetailView.as_view(), name='product_detail'),
    path("products/add_product/", ProductCreateView.as_view(), name="add_product"),
    path("products/<int:pk>/edit/", ProductUpdateView.as_view(), name='product_edit'),
    path("products/<int:pk>/delete/", ProductDeleteView.as_view(), name='product_delete'),
    path("category/<int:pk>/", ProductsCategoryListView.as_view(), name='category'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import RegisterView, UserLoginView, UserProfileEdit

# from .views import ProductListView, ContactFormView, ProductDetailView, ProductCreateView, ProductUpdateView, \
#     ProductDeleteView

app_name = UsersConfig.name

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(next_page='catalog:home'), name='login'),
    path('logout/', LogoutView.as_view(next_page='catalog:home'), name='logout'),
    path('profile/<int:pk>', UserProfileEdit.as_view(), name='profile'),
]

catalog/models.py
from django.db import models

from users.models import User


class Category(models.Model):

    name = models.CharField(max_length=150, verbose_name="Наименование")
    description = models.TextField(verbose_name="Описание")

    def __str__(self):
        return f"{self.name}\n {self.description}"

    class Meta:
        verbose_name = "категория"
        verbose_name_plural = "категории"


class Product(models.Model):

    name = models.CharField(max_length=150, verbose_name="Наименование")
    description = models.TextField(verbose_name="Описание")
    image = models.ImageField(
        upload_to="images/", verbose_name="Изображение", blank=True, null=True
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        verbose_name="Категория товара",
        related_name="users",
    )
    owner = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name="Автор записи",
        related_name="products",
    )
    purchase_price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Цена за покупку")
    is_publish = models.BooleanField(default=False, verbose_name="Статус публикации")
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    def __str__(self):
        return f"{self.name}\n {self.description}"

    class Meta:
        verbose_name = "товар"
        verbose_name_plural = "товары"
        ordering = ["purchase_price"]
        permissions = [
            ("can_unpublish_product", "Сan unpublish product"),

        ]


class StoreContact(models.Model):

    telephone = models.CharField(max_length=20, verbose_name="Телефон для связи")
    email = models.CharField(max_length=50, verbose_name="Электронная почта")
    main_office_address = models.CharField(max_length=200, verbose_name="Адрес офиса")
    office_hours = models.CharField(max_length=200, verbose_name="Время работы офиса")
    tg_contact = models.CharField(max_length=50, verbose_name="Телеграмм")
    whatsapp = models.CharField(max_length=50, verbose_name="Ватсапп")
    instagram = models.CharField(max_length=50, verbose_name="Инстаграмм", blank=True, null=True)

    def __str__(self):
        return f"{self.main_office_address}\n {self.telephone}"

    class Meta:
        verbose_name = "Контакт"
        verbose_name_plural = "Контакты"

catalog/forms.py
from django import forms
from django.core.exceptions import ValidationError

from catalog.custom_validators import ForbiddenWordsValidator
from catalog.models import Product
from users.utils import UserSettingUpMix


class ContactForm(forms.Form):
    user_name = forms.CharField(label="Имя", max_length=100)
    user_email = forms.EmailField(label="Электронная почта")
    user_text = forms.CharField(label="Сообщение", widget=forms.Textarea)


class ProductForm(UserSettingUpMix,forms.ModelForm):
    MAX_UPLOAD_SIZE = 5 * 1024 ** 2
    ALLOWED_TYPES = ['image/jpeg', 'image/png']

    class Meta:
        model = Product
        fields = ['name',
                  'description',
                  'category',
                  'is_publish',
                  'purchase_price',
                  'image']

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        self.validation = ForbiddenWordsValidator()

        for field, field_object in self.fields.items():

            if field == 'description':
                field_object.widget.attrs.update({
                    'cols': '5',
                    'rows': '5'
                })
            elif field == 'purchase_price':
                field_object.widget.attrs.update({'step': '500'})

    def clean_name(self):
        name = self.cleaned_data.get('name')
        self.validation(name)
        return name

    def clean_description(self):
        description = self.cleaned_data.get('description')
        self.validation(description)
        return description

    def clean_purchase_price(self):
        price = self.cleaned_data.get('purchase_price')
        if price <= 0:
            raise ValidationError('Цена должна быть больше 0')
        return price

    def clean_image(self):
        image = self.cleaned_data.get('image')

        if image:
            if image.content_type not in self.ALLOWED_TYPES:
                raise ValidationError('Недопустимый тип файла. Можно загрузить только файлы типов: .jpeg, .png.')

            elif image.size > self.MAX_UPLOAD_SIZE:
                raise ValidationError('Ваше изображение превышает допустимый лимит 5 МВ.')
        return image

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseForbidden

from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.generic import DetailView, UpdateView
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.list import ListView, MultipleObjectMixin
from django.views.generic.edit import FormView, CreateView, DeleteView

from catalog.forms import ContactForm, ProductForm
from catalog.models import Product, StoreContact, Category
from catalog.services import get_products_from_category, get_products_from_cache


class ProductListView(ListView):
    model = Product
    paginate_by = 3
    template_name = "catalog/home.html"
    context_object_name = 'products'

    def get_queryset(self):
        queryset = get_products_from_cache()
        # return queryset.filter(is_publish=True)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = Category.objects.all()
        return context

@method_decorator(cache_page(60), name='dispatch')
class ProductDetailView(DetailView):
    model = Product
    template_name = "catalog/product_detail.html"
    context_object_name = 'product'


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    template_name = "catalog/product_form.html"
    success_url = reverse_lazy("catalog:home")

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    template_name = "catalog/product_form.html"

    def get(self, *args, **kwargs):
        context = super().get(kwargs, args)
        if self.request.user != self.object.owner:
            return HttpResponseForbidden("У вас нет доступа для редактирования товара.")
        return context

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if not self.request.user.has_perm('product.can_unpublish_product'):
            data['form'].fields['is_publish'].disabled=True
            return data
        return data

    def form_valid(self, form):
        page = self.get_context_data()['object'].pk
        self.success_url = reverse_lazy("catalog:product_detail", kwargs={'pk': page})
        return super().form_valid(form)


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product

    def get(self, *args, **kwargs):
        context = super().get(kwargs, args)
        if self.request.user != self.object.owner and not self.request.user.has_perm('product.can_unpublish_product'):
            return HttpResponseForbidden("У вас нет доступа для удаления товара.")
        return context

    # def get_queryset(self, **kwargs):
    #     if not self.request.user.has_perm('product.delete_product'):
    #         raise PermissionDenied("У вас нет доступа для удаления товара.")
    #
    #     return super().get_queryset()

    template_name = "catalog/product_confirm_delete.html"
    success_url = reverse_lazy("catalog:home")


class ContactFormView(FormView):
    template_name = "catalog/contacts.html"
    form_class = ContactForm
    success_url = reverse_lazy("catalog:home")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["store_contact"] = StoreContact.objects.all()[0]
        return context

    def form_valid(self, form):
        print(f'Имя пользователя: {form.cleaned_data["user_name"]}\n'
              f'Адрес электронной почты: {form.cleaned_data["user_email"]}\n'
              f'Сообщение: {form.cleaned_data["user_text"]}')
        return super().form_valid(form)


class ProductsCategoryListView(ListView):
    model = Product
    paginate_by = 3
    template_name = "catalog/home.html"
    context_object_name = 'products'

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        context["categories"] = Category.objects.all()
        context["category"] = Category.objects.filter(pk=self.kwargs['pk'])[0]

        return context

    def get_queryset(self):
        return get_products_from_category(self.kwargs['pk'])

catalog/templates/catalog/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <script defer src="/static/js/bootstrap.bundle.min.js"></script>
</head>

<body>

<div class="row ">
    {% include 'catalog/menu.html' %}
    <div class="col-10 bg-primary-subtle">
        <header>
            <div class="container text-center mt-5">
                <div class="row align-items-start">
                    <div class="col"></div>
                    <div class="col">
                        <p class="h1 text-center">{% block head %}{% endblock %}</p>
                    </div>
                    <div class="col">
                        {% if user.is_authenticated %}
                        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                            {% if request.resolver_match.url_name == 'home' %}
                            <a class="btn btn-success" href="{% url 'catalog:add_product' %}">Добавить товар</a>
                            {%endif%}
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>

            <div class="row">
                <p class="h5 text-center text-secondary">{% block head_description %}{% endblock %}</p>
            </div>
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton5"
                        data-bs-toggle="dropdown" aria-expanded="false">
                    Выбрать категорию
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton5">
                    {% for category in categories %}
                    <li><a class="dropdown-item" href="{% url 'catalog:category' category.pk %}">{{ category.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </header>
        <div class="row mt-2">
            <div class="col-2"></div>
            <div class="col-8">
                {% block content %}{% endblock %}
            </div>
            <div class="col-2"></div>
        </div>

    </div>
</div>
</body>
</html>

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}

{% block title %}Контакты{% endblock %}

{% block head%}Контакты{% endblock %}

{% block head_description %}Для связи с нами, пожалуйста, заполните форму{% endblock %}

{% block content %}

<div class="row mt-5">
    <div class="row mt-5 ">
        <div class="col-1"></div>
        {% include 'catalog\feedback.html' %}
        <div class="col-1"></div>
        <div class="col-5 bg">
            <h2 class="text-left">
                Наши контакты</h2>
            {% if store_contact %}
            <dl class="row mt-5">
                <dt class="col-sm-3">Основной способ связи.</dt>
                <dd class="col-sm-9">Телефон: {{store_contact.telephone}} (бесплатно по России) Операторы работают
                    ежедневно с 9:00 до
                    21:00
                </dd>
                <dt class="col-sm-3">Email:</dt>
                <dd class="col-sm-9">{{store_contact.email}} Ответим на все вопросы в течение рабочего дня</dd>
                <dt class="col-sm-3">Офисы и представительства:</dt>
                <dd class="col-sm-9">
                    <dl class="row">
                        <dt class="col-sm-4">Главный офис:</dt>
                        <dd class="col-sm-8">{{store_contact.main_office_address}}</dd>
                    </dl>
                    <dl class="row">
                        <dt class="col-sm-4">Время работы офиса:</dt>
                        <dd class="col-sm-8">{{store_contact.office_hours}}</dd>
                    </dl>
                </dd>
                <dt class="col-sm-3">Социальные сети и мессенджеры:</dt>
                <dd class="col-sm-9">
                    <dl class="row">
                        <dt class="col-sm-3">Telegram:</dt>
                        <dd class="col-sm-9">{{store_contact.tg_contact}}</dd>
                        <dt class="col-sm-3">WhatsApp:</dt>
                        <dd class="col-sm-9">{{store_contact.whatsapp}}</dd>
                        <dt class="col-sm-3">Instagram:</dt>
                        <dd class="col-sm-9">{{store_contact.instagram}}</dd>
                    </dl>
                </dd>
            </dl>
            {% else %}
            <p>No contacts are available.</p>
            {% endif %}
        </div>
        <div class="col-1"></div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/feedback.html
<!--Форма обратной связи пользователя-->

<div class="col-4 border rounded-2 bg-info-subtle">
    <form action="" method="POST">
        {% csrf_token %}
        <div class="mb-3 mt-3">
            <label for="{{ form.user_name.id_for_label }}" class="form-label">{{ form.user_name.label }}</label>
            <input type="text" class="form-control" id="{{ form.user_name.id_for_label }}" name="{{ form.user_name.name }}" >
        </div>
        <div class="mb-3">
            <label for="basic-addon1" class="form-label">{{ form.user_email.label }}</label>
            <div class="input-group">
                <span class="input-group-text" id="basic-addon1">@</span>
                <input type="email" class="form-control" aria-describedby="basic-addon1"
                       name="{{ form.user_email.name }}">
            </div>
        </div>
        <div class="mb-3">
            <label for="{{ form.user_text.id_for_label }}" class="form-label">{{ form.user_text.label }}</label>
            <textarea class="form-control" id="{{ form.user_text.id_for_label }}" rows="3"
                      name="{{ form.user_text.name }}"></textarea>
        </div>
        <button type="submit" class="btn btn-primary mb-2">Отправить</button>
    </form>
</div>

catalog/templates/catalog/menu.html
<div class="col text-bg-dark p-3">
    <div class="vstack gap-3 text-start">
        <button type="button" class="btn btn-dark btn-lg bg-dark fs-4 fw-bold">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                 class="bi bi-bootstrap-fill" viewBox="0 0 16 16">
                <path d="M6.375 7.125V4.658h1.78c.973 0 1.542.457 1.542 1.237 0 .802-.604 1.23-1.764 1.23zm0 3.762h1.898c1.184 0 1.81-.48 1.81-1.377 0-.885-.65-1.348-1.886-1.348H6.375z"/>
                <path d="M4.002 0a4 4 0 0 0-4 4v8a4 4 0 0 0 4 4h8a4 4 0 0 0 4-4V4a4 4 0 0 0-4-4zm1.06 12V3.545h3.399c1.587 0 2.543.809 2.543 2.11 0 .884-.65 1.675-1.483 1.816v.1c1.143.117 1.904.931 1.904 2.033 0 1.488-1.084 2.396-2.888 2.396z"/>
            </svg>
            Меню
        </button>
        <hr class="divider">
        <div class="btn-group-vertical ">
            <a class="btn btn-dark text-light btn-outline-primary border-dark fs-5" href="{% url 'catalog:home' %}"
               role="button">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-house-door"
                     viewBox="0 0 16 16">
                    <path d="M8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4.5a.5.5 0 0 0 .5-.5v-4h2v4a.5.5 0 0 0 .5.5H14a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293zM2.5 14V7.707l5.5-5.5 5.5 5.5V14H10v-4a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v4z"/>
                </svg>
                Главная</a>
            <a class="btn btn-dark text-light text-left btn-outline-primary border-dark fs-5"
               href="" role="button">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-receipt-cutoff" viewBox="0 0 16 16">
                    <path d="M3 4.5a.5.5 0 0 1 .5-.5h6a.5.5 0 1 1 0 1h-6a.5.5 0 0 1-.5-.5m0 2a.5.5 0 0 1 .5-.5h6a.5.5 0 1 1 0 1h-6a.5.5 0 0 1-.5-.5m0 2a.5.5 0 0 1 .5-.5h6a.5.5 0 1 1 0 1h-6a.5.5 0 0 1-.5-.5m0 2a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 0 1h-6a.5.5 0 0 1-.5-.5m0 2a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 0 1h-6a.5.5 0 0 1-.5-.5M11.5 4a.5.5 0 0 0 0 1h1a.5.5 0 0 0 0-1zm0 2a.5.5 0 0 0 0 1h1a.5.5 0 0 0 0-1zm0 2a.5.5 0 0 0 0 1h1a.5.5 0 0 0 0-1zm0 2a.5.5 0 0 0 0 1h1a.5.5 0 0 0 0-1zm0 2a.5.5 0 0 0 0 1h1a.5.5 0 0 0 0-1z"/>
                    <path d="M2.354.646a.5.5 0 0 0-.801.13l-.5 1A.5.5 0 0 0 1 2v13H.5a.5.5 0 0 0 0 1h15a.5.5 0 0 0 0-1H15V2a.5.5 0 0 0-.053-.224l-.5-1a.5.5 0 0 0-.8-.13L13 1.293l-.646-.647a.5.5 0 0 0-.708 0L11 1.293l-.646-.647a.5.5 0 0 0-.708 0L9 1.293 8.354.646a.5.5 0 0 0-.708 0L7 1.293 6.354.646a.5.5 0 0 0-.708 0L5 1.293 4.354.646a.5.5 0 0 0-.708 0L3 1.293zm-.217 1.198.51.51a.5.5 0 0 0 .707 0L4 1.707l.646.647a.5.5 0 0 0 .708 0L6 1.707l.646.647a.5.5 0 0 0 .708 0L8 1.707l.646.647a.5.5 0 0 0 .708 0L10 1.707l.646.647a.5.5 0 0 0 .708 0L12 1.707l.646.647a.5.5 0 0 0 .708 0l.509-.51.137.274V15H2V2.118z"/>
                </svg>
                Категории</a>
            <button type="button" class="btn btn-dark text-light btn-outline-primary border-dark fs-5">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-cart-check-fill" viewBox="0 0 16 16">
                    <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0m7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0m-1.646-7.646-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L8 8.293l2.646-2.647a.5.5 0 0 1 .708.708"/>
                </svg>
                Заказы
            </button>
            <a class="btn btn-dark text-light text-left btn-outline-primary border-dark fs-5"
               href="{% url 'catalog:contacts' %}" role="button">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-person-lines-fill" viewBox="0 0 16 16">
                    <path d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6m-5 6s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zM11 3.5a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1h-4a.5.5 0 0 1-.5-.5m.5 2.5a.5.5 0 0 0 0 1h4a.5.5 0 0 0 0-1zm2 3a.5.5 0 0 0 0 1h2a.5.5 0 0 0 0-1zm0 3a.5.5 0 0 0 0 1h2a.5.5 0 0 0 0-1z"/>
                </svg>
                Контакты</a>
        </div>
        <div class="d-flex flex-column text-center" style="height: 73vh">
            <hr class="divider mt-auto p-3">
            <div class="row">
                <div class="dropdown ">
                    {% if user.is_authenticated %}
                    <button class="btn text-light dropdown-toggle fs-5" type="button"
                            id="dropdownMenuButton1"
                            data-bs-toggle="dropdown" aria-expanded="false">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                             class="bi bi-person-fill" viewBox="0 0 16 16">
                            <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3Zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z"/>
                        </svg>
                        {{user.first_name}} {{user.last_name}}
                    </button>
                    <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownMenuButton1">

                        <li class="nav-item">
                            <form method="post" action="{% url 'users:logout'%}" style="display: inline">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger dropdown-item">Выйти</button>
                            </form>
                        </li>
                        <li><a class="dropdown-item" href="{% url 'users:profile' user.pk%}">Профиль</a></li>
                    </ul>
                    {% else %}
                    <button class="btn text-light dropdown-toggle fs-5" type="button"
                            id="dropdownMenuButton2"
                            data-bs-toggle="dropdown" aria-expanded="false">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                             class="bi bi-person-fill" viewBox="0 0 16 16">
                            <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3Zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z"/>
                        </svg>
                        Профиль
                    </button>
                    <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownMenuButton2">
                        <li class="nav-item">
                            <a class="dropdown-item border-outline-success" aria-current="page"
                               href="{% url 'users:login'%}">Войти</a>
                        <li class="nav-item">
                            <a class="dropdown-item" aria-current="page"
                               href="{% url 'users:register'%}">Регистрация</a>
                    </ul>
                    {% endif%}
                </div>
            </div>
        </div>
    </div>
</div>

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block title %}Удалить товар{% endblock %}

{% block head%}Вы уверены, что хотите удалить этот товар?{% endblock %}


{% block content %}


<div class="d-flex justify-content-center mt-5">
    <div class=" row-cols-1">
        <div class="col"><h2>{{ product.name }}</h2></div>
        <div class="d-flex justify-content-center mt-5">
            <form method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Удалить</button>
                <a href="{% url 'catalog:product_detail' object.pk %}" class="btn btn-primary">Отмена</a>
            </form>
        </div>
    </div>
</div>


{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}

{% block title %}{{ product.name }}{% endblock %}

{% block head%}{{ product.name }}{% endblock %}


{% block content %}
<header>
    <h1 class="text-center">Подробная информация о товаре:</h1>
</header>
{% if product %}
<div class="d-flex justify-content-center mt-5">
    <div class="card text-center align-middle" style="max-width: 1050px">
        <div class="card-header h5">
            <strong>{{ product.name }}</strong>
        </div>
        <div class="card-body">
            <p class="card-text  py-2"><strong>{{product.description }} </strong></p>
            <h5 class="card-title h1">ЦЕНА: {{ product.purchase_price }} РУБ.</h5>
        </div>
        <div class="card-footer">
            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                {% if user == product.owner %}
                <a href="{% url 'catalog:product_edit' object.pk %}"
                   class="btn btn-primary text-light border-dark w-100 mt-4">Изменить</a>
                <a href="{% url 'catalog:product_delete' object.pk %}"
                   class="btn btn-danger text-light border-dark w-100 mt-4">Удалить</a>
                {% elif perms.catalog.can_unpublish_product %}
                <a href="{% url 'catalog:product_delete' object.pk %}"
                   class="btn btn-danger text-light border-dark w-100 mt-4">Удалить</a>
                {% endif %}
            </div>
            <div class="row">
                <div><a href="#" class="btn btn-success text-light border-dark w-100 mt-4">Купить</a></div>
            </div>
        </div>
    </div>
    <div class="col-1"></div>
    <div class="col-6">
        {% if product.image %}
        <img src="{{ product.image.url }}" class="card-img-top" alt="{{product.name}}">
        {% else %}
        {% load static %}
        <img src="{% static 'default_img/product.webp' %}" class="object-fit-sm-contain border rounded"
             alt="{{product.name}}">
        {% endif %}
    </div>
    {% else %}
    <div class="container text-center">
        <h2>Товар не найден</h2>
    </div>
</div>
{% endif %}
{% endblock %}